services:
  jekyll:
    build: .
    entrypoint: sh
    command: [ "-c", "bundle install && bundle exec jekyll serve --host 0.0.0.0" ]
    working_dir: /srv/jekyll
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
